apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-spa
  namespace: cc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
      - name: c-spa
        image: sdmhmi/spa
        ports:
        - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: service-spa
  namespace: cc-ns
  labels:
    app: spa
spec:
  selector:
    app: spa
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-conveyor
  namespace: cc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conveyor      
  template:
    metadata:
      labels:
        app: conveyor
    spec:
      containers:
      - name: c-conveyor
        image: sdmhmi/conveyor
        ports:
        - containerPort: 8081 
---
apiVersion: v1
kind: Service
metadata:
  name: service-conveyor
  namespace: cc-ns
  labels:
    app: conveyor
spec:
  selector:
    app: conveyor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sorting
  namespace: cc-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sorting
  template:
    metadata:
      labels:
        app: sorting
    spec:
      containers:
      - name: c-sorting
        image: sdmhmi/sorting
        ports:
        - containerPort: 8082 

---
apiVersion: v1
kind: Service
metadata:
  name: service-sorting
  namespace: cc-ns
  labels:
    app: sorting
spec:
  selector:
    app: sorting
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-picking
  namespace: cc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picking
  template:
    metadata:
      labels:
        app: picking
    spec:
      containers:
      - name: c-picking
        image: sdmhmi/picking
        ports:
        - containerPort: 8083 

---
apiVersion: v1
kind: Service
metadata:
  name: service-picking
  namespace: cc-ns
  labels:
    app: picking
spec:
  selector:
    app: picking
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
