apiVersion: v1
kind: Service
metadata:
  name: my-service-spa
  labels:
    app: label-spa
spec:
  selector:
    app: label-spa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-conveyor
  labels:
    app: label-conveyor
spec:
  selector:
    app: label-conveyor
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
      
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-sorting
  labels:
    app: label-sorting
spec:
  selector:
    app: label-sorting
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-picking
  labels:
    app: label-picking
spec:
  selector:
    app: label-picking
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8083
      
